blogs/urls.py
from django.urls import path
from . import views


app_name = 'blogs'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('inquiry/', views.InquiryView.as_view(), name='inquiry'),
    path('blog_list/', views.BlogListView.as_view(), name='blog_list'),
    path('blog_detail/<int:pk>/', views.BlogDetailView.as_view(), name='blog_detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogs.urls')),
    path('accounts/', include('allauth.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
class CustomUser(AbstractUser):
    """Model definition for CustomUser."""

    class Meta:
        verbose_name_plural = 'CustomUsers'

    def __str__(self):
        return self.username

blogs/models.py
from django.db import models

from accounts.models import CustomUser


# Create your models here.
class Blog(models.Model):
    """Model definition for Blog."""

    # params
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.PROTECT)
    title = models.CharField(verbose_name='タイトル', max_length=40)
    content = models.TextField(verbose_name='本文', blank=True, null=True)
    photo1 = models.ImageField(verbose_name='写真1', blank=True, null=True)
    photo2 = models.ImageField(verbose_name='写真2', blank=True, null=True)
    photo3 = models.ImageField(verbose_name='写真3', blank=True, null=True)
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=False)

    class Meta:
        verbose_name_plural = 'Blog'

    def __str__(self):
        return self.title

blogs/forms.py
from django import forms
from django.core.mail import EmailMessage


class InquiryForm(forms.Form):
    """InquiryForm definition."""

    # params
    name = forms.CharField(label='お名前', max_length = 30)
    email = forms.EmailField(label='メールアドレス')
    title = forms.CharField(label='タイトル', max_length = 30)
    message = forms.CharField(label='メッセージ', widget=forms.Textarea)
    
    # add class/placeholder
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['name'].widget.attrs['class'] = 'form-control col-9'
        self.fields['name'].widget.attrs['placeholder'] = 'お名前をここに入力してください。'
        self.fields['email'].widget.attrs['class'] = 'form-control col-11'
        self.fields['email'].widget.attrs['placeholder'] = 'メールアドレスをここに入力してください。'
        self.fields['title'].widget.attrs['class'] = 'form-control col-11'
        self.fields['title'].widget.attrs['placeholder'] = 'タイトルをここに入力してください。'
        self.fields['message'].widget.attrs['class'] = 'form-control col-12'
        self.fields['message'].widget.attrs['placeholder'] = 'メッセージをここに入力してください。'
        
    # send email
    def send_email(self):
        
        # value
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        title = self.cleaned_data['title']
        message = self.cleaned_data['message']
        
        # format
        subject = f'お問い合わせ {title}'
        message = f'送信者名: {name}\nメールアドレス: {email}\nメッセージ: {message}'

        # mail setting
        from_email = 'admin@example.com'
        to_list = [
            'test@example.com'
        ]
        cc_list = [
            email
        ]
        
        # send
        message =EmailMessage(subject=subject, body=message, from_email=from_email, to=to_list, cc=cc_list)
        message.send()

accounts/views.py
from django.shortcuts import render

# Create your views here.

blogs/views.py
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
import logging
from django.contrib import messages

from django.views import View
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Blog
from .forms import InquiryForm


# logging
logger = logging.getLogger(__name__)


# index
class Index(generic.TemplateView):
    template_name = 'blogs/index.html'


# お問い合わせ
class InquiryView(generic.FormView):
    template_name = 'blogs/inquiry.html'
    form_class = InquiryForm
    success_url = reverse_lazy('blogs:inquiry')
    
    def form_valid(self, form):
        form.send_email()
        messages.success(self.request, 'メッセージを送信しました。')
        logger.info(f'Inquiry sent by {form.cleaned_data["name"]}')
        return super().form_valid(form)
    
    
# ブログ一覧
class BlogListView(LoginRequiredMixin, generic.ListView):
    model = Blog
    template_name = "blog:blog_list.html"
    paginate_by = 2

    def get_queryset(self):
        blogs = Blog.objects.filter(user=self.request.user).order_by('-created_at')
        return blogs
    
    
# detail
class BlogDetailView(LoginRequiredMixin, generic.DetailView):
    model = Blog
    template_name = "blogs/blog_detail.html"

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">

<head>
  <!-- base -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>{% block title %}{% endblock title %}</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/one-page-wonder.min.css' %}" rel="stylesheet">

  <!-- My style -->
  <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">

  <!-- extra head -->
  {% block head %}{% endblock head %}
</head>

<body>
  <div id="wrapper">
    
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
      <div class="container">

        <!-- brand -->
        <a class="navbar-brand" href="{% url 'blogs:index' %}">Start MyBlog</a>

        <!-- hamburger -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- nav -->
        <div class="collapse navbar-collapse" id="navbarResponsive">
          
          <!-- additional -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item {% block active_inquiry %}{% endblock active_inquiry %}">
              <a href="{% url 'blogs:inquiry' %}" class="nav-link">INQUIRY</a>
            </li>
            {% if user.is_authenticated %}
              <li class="nav-item {% block active_blog_list %}{% endblock %}">
                <a href="{% url 'blogs:blog_list' %}" class="nav-link">BLOG LIST</a>
              </li>
            {% endif %}
          </ul>

          <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a href="{% url 'account_logout' %}" class="nav-link">Logout</a>
              </li>
            {% else %}
              <li class="nav-item {% block active_signup %}{% endblock %}">
                <a class="nav-link" href="{% url 'account_signup' %}">Signup</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'account_login' %}">Loginn</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <!-- header -->
    {% block header %}{% endblock header %}

    <!-- messages -->
    {% if messages %}
      <div class="container">
        <div class="row">
          <div class="my-div-style w-100">
            <ul class="messages" style="list-style: none;">
              {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>
                  {{ message }}
                </li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    {% endif %}
      

    <!-- main -->
    {% block content %}{% endblock content %}

    <!-- Footer -->
    <footer class="py-5 bg-black">
      <div class="container">
        <p class="m-0 text-center text-white small">Copyright &copy; Your Website 2019</p>
      </div>
      <!-- /.container -->
    </footer>
  </div>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>
</html>

templates/blogs/blog_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}日記詳細{% endblock title %}

{% block active_blog_list %}active{% endblock active_blog_list %}


{% block content %}
  <div class="container">
    <div class="my-div-style w-100">
      <div class="row">
        <div class="col-3">
          <strong>タイトル</strong>
        </div>
        <div class="col-9">
          {{ object.title }}
        </div>
      </div>

      <hr>

      <div class="row">
        <div class="col-3">
          <strong>本文</strong>
        </div>
        <div class="col-9">
          {{ object.content|linebreaksbr }}
        </div>
      </div>

      <div class="row">
        <div class="col-3">
          <strong>写真</strong>
        </div>
        <div class="col-3">
          <img src="{% if object.photo1 %}{{ object.photo1.url }}{% elif object.photo2 %}{{ object.photo2.url }}{% elif object.photo3 %}{{ object.photo3.url }}{% endif %}" alt="blog-image" width="200">
        </div>
      </div>

      <hr>

      <div class="row">
        <div class="col-3">
          <strong>作成日時</strong>
        </div>
        <div class="col-9">
          {{ object.created_at }}
        </div>
      </div>

      <hr>

      <div class="row">
        <div class="col-3">
          <strong>更新日時</strong>
        </div>
        <div class="col-9">
          {{ object.updated_at }}
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/blogs/blog_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}ブログリスト{% endblock title %}

{% block active_diary_list %}active{% endblock active_diary_list %}


<!-- head -->
{% block head %}
  <link rel="stylesheet" href="{% static 'css/clean-blog.css' %}">  
{% endblock head %}


<!-- content -->
{% block content %}
  <div class="container">
    <div class="row">
      <div class="my-div-style w-100">
        <div class="col-lg-8 col-md-10 mx-auto">

          <!-- new -->
          <div class="clearfix">
            <a href="#" class="btn btn-primary float-right">新規作成</a>
          </div>
  
          <!-- list -->
          {% for blog in object_list %}
            <div class="post-preview">
              <a href="{% url 'blogs:blog_detail' blog.id %}">
                <h2 class="post-title">
                  {{ blog.title }}
                </h2>
                <h3 class="post-subtitle">
                  {{ blog.content|truncatechars:20 }}
                </h3>
              </a>
              <p class="post-meta">{{ blog.created_at }}</p>
            </div>
            <hr>
          {% empty %}
            <p>日記がありません。</p>
          {% endfor %}
          
          <!-- pagenation -->
          {% if is_paginated %}
            <ul class="pagination">
              <!-- 前ページのリンク -->
              {% if page_obj.has_previous %}
                <li class="page-item">
                  <a href="?page={{ page_obj.previous_page_number }}" class="page-link">
                    <span aria-hidden="true">&laquo;</span>
                  </a>
                </li>
              {% endif %}

              <!-- ページ数表示 -->
              {% for page_num in page_obj.paginator.page_range %}
                {% if page_obj.number == page_num %}
                  <li class="page-item active">
                    <a href="#" class="page-link">{{ page_num }}</a>
                  </li>
                {% else %}
                  <li class="page-item">
                    <a href="?page={{ page_num }}" class="page-link">{{ page_num }}</a>
                  </li>
                {% endif %}
              {% endfor %}
          
              <!-- 次ページのリンク -->
              {% if page_obj.has_next %}
                <li class="page-item">
                  <a href="?page={{ page_obj.next_page_number }}" class="page-link">
                    <span aria-hidden="true">&raquo;</span>
                  </a>
                </li>
              {% endif %}
            </ul>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock content %}


  

templates/blogs/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}blogs{% endblock title %}

{% block header %}
  <header class="masthead text-center text-white">
    <div class="masthead-content">
      <div class="container">
        <h1 class="masthead-heading mb-0">My Blogs</h1>
        <h2 class="masthead-subheading mb-0">ブログ作成サービス</h2>
        <a href="{% url 'account_login' %}" class="btn btn-primary btn-xl rounded-pill mt-5">Login</a>
      </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
  </header>
{% endblock header %}


{% block content %}
  <section>
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-6 order-lg-2">
          <div class="p-5">
            <img class="img-fluid rounded-circle" src="{% static 'img/01.jpg' %}" alt="">
          </div>
        </div>
        <div class="col-lg-6 order-lg-1">
          <div class="p-5">
            <h2 class="display-4">My blogs</h2>
            <p>あなただけのブログが作成できる</p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section>
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-6">
          <div class="p-5">
            <img class="img-fluid rounded-circle" src="{% static 'img/02.jpg' %}" alt="">
          </div>
        </div>
        <div class="col-lg-6">
          <div class="p-5">
            <h2 class="display-4">New days for You!</h2>
            <p>日々の出来事を書き上げよう！</p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section>
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-6 order-lg-2">
          <div class="p-5">
            <img class="img-fluid rounded-circle" src="{% static 'img/03.jpg' %}" alt="">
          </div>
        </div>
        <div class="col-lg-6 order-lg-1">
          <div class="p-5">
            <h2 class="display-4">Join us and enjoy new Living!</h2>
            <p>さあ、あなただけの出来事を創り出そう！</p>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

templates/blogs/inquiry.html
{% extends 'base.html' %}

{% block titile %}お問い合わせ{% endblock %}

{% block active_inquiry %}active{% endblock active_inquiry %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="my-div-style">
        <form action="" method="POST">
        {% csrf_token %}
          
          <!-- error -->
          {{ form.non_field_errors }}
          
          <!-- form field -->
          {% for field in form %}
            <div class="form-group row">
              <label for="{{ field.id_for_lavel }}" class="col-sm-4 col-form-label">
                <strong>{{ field.label_tag }}</strong>
              </label>
              <div class="col-sm-8">
                {{ field }}
                {{ field.errors }}
              </div>
            </div>
          {% endfor %}
          
          <!-- button -->
          <div class="offset-sm-4 col-sm-8">
            <button class="btn btn-primary" type="submit">送信</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock content %}